import { describe, it, expect } from 'vitest';
import { generateSieveScript } from '../sieveGenerator';
import type { SieveRule } from '../../types/sieve';

describe('sieveGenerator', () => {
  const createRule = (overrides: Partial<SieveRule> = {}): SieveRule => ({
    id: 'rule-1',
    name: 'Test Rule',
    enabled: true,
    conditions: [],
    conditionOperator: 'allOf',
    actions: [{ type: 'keep' }],
    ...overrides,
  });

  describe('generateSieveScript', () => {
    it('should generate empty script for empty rules', () => {
      const script = generateSieveScript([]);
      expect(script).toContain('Generated by Sagittarius');
      expect(script).toContain('Do not edit manually');
    });

    it('should skip disabled rules', () => {
      const rules = [
        createRule({ enabled: false, name: 'Disabled Rule' }),
      ];
      const script = generateSieveScript(rules);
      expect(script).not.toContain('Disabled Rule');
    });

    it('should include rule name as comment', () => {
      const rules = [createRule({ name: 'My Rule' })];
      const script = generateSieveScript(rules);
      expect(script).toContain('# Rule: My Rule');
    });

    it('should require fileinto extension', () => {
      const rules = [
        createRule({
          actions: [{ type: 'fileinto', value: 'Archive' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('require ["fileinto"]');
    });

    it('should require imap4flags extension for flag action', () => {
      const rules = [
        createRule({
          actions: [{ type: 'flag' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('require ["imap4flags"]');
    });

    it('should require vacation extension', () => {
      const rules = [
        createRule({
          actions: [{ type: 'vacation', value: 'I am out of office' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('require ["vacation"]');
    });

    it('should require multiple extensions', () => {
      const rules = [
        createRule({
          actions: [
            { type: 'fileinto', value: 'Archive' },
            { type: 'flag' },
          ],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('require ["fileinto", "imap4flags"]');
    });

    it('should not require extensions for built-in actions', () => {
      const rules = [
        createRule({
          actions: [
            { type: 'keep' },
            { type: 'discard' },
            { type: 'redirect', value: 'other@example.com' },
          ],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).not.toContain('require');
    });

    it('should generate fileinto action', () => {
      const rules = [
        createRule({
          actions: [{ type: 'fileinto', value: 'Work' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('fileinto "Work"');
    });

    it('should escape quotes in folder names', () => {
      const rules = [
        createRule({
          actions: [{ type: 'fileinto', value: 'Folder "Important"' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('fileinto "Folder \\"Important\\""');
    });

    it('should escape backslashes in folder names', () => {
      const rules = [
        createRule({
          actions: [{ type: 'fileinto', value: 'Folder\\Path' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('fileinto "Folder\\\\Path"');
    });

    it('should generate discard action', () => {
      const rules = [
        createRule({ actions: [{ type: 'discard' }] }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('discard;');
    });

    it('should generate keep action', () => {
      const rules = [
        createRule({ actions: [{ type: 'keep' }] }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('keep;');
    });

    it('should generate redirect action', () => {
      const rules = [
        createRule({
          actions: [{ type: 'redirect', value: 'backup@example.com' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('redirect "backup@example.com"');
    });

    it('should generate flag action', () => {
      const rules = [
        createRule({ actions: [{ type: 'flag' }] }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('addflag "\\\\Flagged"');
    });

    it('should generate vacation action', () => {
      const rules = [
        createRule({
          actions: [{ type: 'vacation', value: 'On vacation until Jan 1' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('vacation "On vacation until Jan 1"');
    });

    it('should generate conditional rule with from condition', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'from', operator: 'contains', value: 'boss@company.com' }],
          actions: [{ type: 'fileinto', value: 'Priority' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('if header :contains "From" "boss@company.com"');
    });

    it('should generate conditional rule with to condition', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'to', operator: 'is', value: 'support@company.com' }],
          actions: [{ type: 'fileinto', value: 'Support' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('header :is "To" "support@company.com"');
    });

    it('should generate conditional rule with subject condition', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'subject', operator: 'matches', value: '*urgent*' }],
          actions: [{ type: 'flag' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('header :matches "Subject" "*urgent*"');
    });

    it('should generate conditional rule with header condition', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'header', operator: 'contains', value: 'X-Priority: 1' }],
          actions: [{ type: 'fileinto', value: 'High Priority' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('header :contains "X-Header" "X-Priority: 1"');
    });

    it('should generate conditional rule with size condition', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'size', operator: 'greater-than', value: '1048576' }],
          actions: [{ type: 'fileinto', value: 'Large' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('size :over 1048576');
    });

    it('should generate conditional rule with size less-than', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'size', operator: 'less-than', value: '1024' }],
          actions: [{ type: 'fileinto', value: 'Small' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('size :under 1024');
    });

    it('should generate rule with not-contains operator', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'from', operator: 'not-contains', value: 'spam' }],
          actions: [{ type: 'keep' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('not header :contains "From" "spam"');
    });

    it('should generate allof condition block for allOf operator', () => {
      const rules = [
        createRule({
          conditionOperator: 'allOf',
          conditions: [
            { field: 'from', operator: 'contains', value: 'company.com' },
            { field: 'subject', operator: 'contains', value: 'invoice' },
          ],
          actions: [{ type: 'fileinto', value: 'Invoices' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('allof(');
      expect(script).toContain('header :contains "From" "company.com"');
      expect(script).toContain('header :contains "Subject" "invoice"');
    });

    it('should generate anyof condition block for anyOf operator', () => {
      const rules = [
        createRule({
          conditionOperator: 'anyOf',
          conditions: [
            { field: 'from', operator: 'contains', value: 'alice@example.com' },
            { field: 'from', operator: 'contains', value: 'bob@example.com' },
          ],
          actions: [{ type: 'fileinto', value: 'Friends' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('anyof(');
    });

    it('should handle single condition without operator wrapper', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'from', operator: 'contains', value: 'test' }],
          actions: [{ type: 'keep' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('if header :contains "From" "test"');
      expect(script).not.toContain('allof');
      expect(script).not.toContain('anyof');
    });

    it('should generate unconditional rule when no conditions', () => {
      const rules = [
        createRule({
          conditions: [],
          actions: [{ type: 'fileinto', value: 'All' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('{');
      expect(script).not.toContain('if');
    });

    it('should generate multiple actions', () => {
      const rules = [
        createRule({
          actions: [
            { type: 'fileinto', value: 'Archive' },
            { type: 'flag' },
          ],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('fileinto "Archive"');
      expect(script).toContain('addflag');
    });

    it('should require relational extension for size conditions', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'size', operator: 'greater-than', value: '1000' }],
          actions: [{ type: 'keep' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('require ["relational"]');
    });

    it('should handle empty action value', () => {
      const rules = [
        createRule({
          actions: [{ type: 'fileinto', value: '' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('fileinto "INBOX"');
    });

    it('should escape special characters in values', () => {
      const rules = [
        createRule({
          conditions: [{ field: 'subject', operator: 'contains', value: 'say "hello"' }],
          actions: [{ type: 'keep' }],
        }),
      ];
      const script = generateSieveScript(rules);
      expect(script).toContain('say \\"hello\\"');
    });
  });
});
