import type { SieveRule, SieveCondition, SieveAction } from '../types/sieve';

// ---------------------------------------------------------------------------
// Sieve script parser — best-effort / regex-based.
// Handles scripts generated by sieveGenerator.ts and simple hand-written ones.
// ---------------------------------------------------------------------------

function generateId(): string {
  return Math.random().toString(36).slice(2, 10);
}

// Strip line comments (#...) and block comments (/* ... */)
function stripComments(script: string): string {
  // block comments
  let s = script.replace(/\/\*[\s\S]*?\*\//g, '');
  // line comments
  s = s.replace(/#[^\n]*/g, '');
  return s;
}

// Extract the content between the outer braces of an `if` block.
// Returns { condition: string; body: string; rest: string } or null.
function extractIfBlock(text: string): { condition: string; body: string; rest: string } | null {
  const ifMatch = text.match(/\bif\s+([\s\S]+?)\s*\{/);
  if (!ifMatch) return null;

  const conditionStr = ifMatch[1];
  const braceStart = (ifMatch.index ?? 0) + ifMatch[0].length - 1; // index of '{'

  // Walk forward to find matching closing brace
  let depth = 0;
  let closeIdx = -1;
  for (let i = braceStart; i < text.length; i++) {
    if (text[i] === '{') depth++;
    else if (text[i] === '}') {
      depth--;
      if (depth === 0) {
        closeIdx = i;
        break;
      }
    }
  }

  if (closeIdx === -1) return null;

  const body = text.slice(braceStart + 1, closeIdx);
  const rest = text.slice(closeIdx + 1);

  return { condition: conditionStr.trim(), body: body.trim(), rest: rest.trim() };
}

// Parse a condition block into SieveCondition[]
function parseConditions(condStr: string): { conditions: SieveCondition[]; operator: 'allOf' | 'anyOf' } {
  let operator: 'allOf' | 'anyOf' = 'allOf';
  let testsStr = condStr;

  const allofMatch = condStr.match(/^allof\s*\(([\s\S]+)\)$/i);
  const anyofMatch = condStr.match(/^anyof\s*\(([\s\S]+)\)$/i);

  if (allofMatch) {
    operator = 'allOf';
    testsStr = allofMatch[1];
  } else if (anyofMatch) {
    operator = 'anyOf';
    testsStr = anyofMatch[1];
  }

  const conditions: SieveCondition[] = [];

  // Match individual tests: header :contains "Hdr" "value"  or  size :over N
  const headerRe = /(not\s+)?header\s+(:is|:contains|:matches)\s+"([^"]+)"\s+"([^"]*)"/gi;
  let m: RegExpExecArray | null;

  while ((m = headerRe.exec(testsStr)) !== null) {
    const negate = !!m[1];
    const matchType = m[2].toLowerCase();
    const headerName = m[3].toLowerCase();
    const value = m[4];

    let field: SieveCondition['field'] = 'header';
    if (headerName === 'from') field = 'from';
    else if (headerName === 'to') field = 'to';
    else if (headerName === 'subject') field = 'subject';

    let operator: SieveCondition['operator'] = 'contains';
    if (negate) {
      operator = 'not-contains';
    } else if (matchType === ':is') {
      operator = 'is';
    } else if (matchType === ':matches') {
      operator = 'matches';
    }

    conditions.push({ field, operator, value });
  }

  // size :over / :under
  const sizeRe = /size\s+(:over|:under)\s+(\d+)/gi;
  while ((m = sizeRe.exec(testsStr)) !== null) {
    const op = m[1].toLowerCase() === ':over' ? 'greater-than' : 'less-than';
    conditions.push({ field: 'size', operator: op, value: m[2] });
  }

  return { conditions, operator };
}

// Parse the action body of an if-block into SieveAction[]
function parseActions(body: string): SieveAction[] {
  const actions: SieveAction[] = [];

  // fileinto "folder";
  const fileintoRe = /fileinto\s+"([^"]+)"\s*;/gi;
  let m: RegExpExecArray | null;
  while ((m = fileintoRe.exec(body)) !== null) {
    actions.push({ type: 'fileinto', value: m[1] });
  }

  // redirect "addr";
  const redirectRe = /redirect\s+"([^"]+)"\s*;/gi;
  while ((m = redirectRe.exec(body)) !== null) {
    actions.push({ type: 'redirect', value: m[1] });
  }

  // discard;
  if (/\bdiscard\s*;/i.test(body)) {
    actions.push({ type: 'discard' });
  }

  // keep;
  if (/\bkeep\s*;/i.test(body)) {
    actions.push({ type: 'keep' });
  }

  // addflag "\\Flagged";
  if (/addflag\s+"\\\\Flagged"\s*;/i.test(body)) {
    actions.push({ type: 'flag' });
  }

  // vacation "...";
  const vacRe = /vacation\s+"([^"]+)"\s*;/gi;
  while ((m = vacRe.exec(body)) !== null) {
    actions.push({ type: 'vacation', value: m[1] });
  }

  return actions;
}

/**
 * Parse a Sieve script text into SieveRule[].
 * Best-effort: returns empty array if parsing fails entirely.
 */
export function parseSieveScript(script: string): SieveRule[] {
  try {
    const cleaned = stripComments(script);
    const rules: SieveRule[] = [];
    let remaining = cleaned.trim();
    let ruleIndex = 0;

    while (remaining.length > 0) {
      const block = extractIfBlock(remaining);
      if (!block) break;

      const { conditions, operator } = parseConditions(block.condition);
      const actions = parseActions(block.body);

      rules.push({
        id: generateId(),
        name: `Rule ${++ruleIndex}`,
        enabled: true,
        conditions,
        conditionOperator: operator,
        actions,
      });

      remaining = block.rest;
    }

    return rules;
  } catch {
    return [];
  }
}
