import type { SieveRule, SieveCondition, SieveAction } from '../types/sieve';

// --- helpers -----------------------------------------------------------

function collectRequires(rules: SieveRule[]): string[] {
  const exts = new Set<string>();

  for (const rule of rules) {
    for (const action of rule.actions) {
      switch (action.type) {
        case 'fileinto':
          exts.add('fileinto');
          break;
        case 'flag':
          exts.add('imap4flags');
          break;
        case 'vacation':
          exts.add('vacation');
          break;
        case 'redirect':
        case 'discard':
        case 'keep':
          // built-in; no require needed
          break;
      }
    }

    for (const cond of rule.conditions) {
      if (cond.field === 'size') {
        // :over / :under are built-in relational tests; require relational for portability
        exts.add('relational');
        exts.add('comparator-i;ascii-numeric');
      }
      if (cond.operator === 'matches') {
        // :matches uses wildcards — part of the base spec, no extra require
      }
    }
  }

  return Array.from(exts);
}

// Map a field name to the Sieve header string
function fieldToHeader(field: SieveCondition['field']): string {
  switch (field) {
    case 'from':
      return 'From';
    case 'to':
      return 'To';
    case 'subject':
      return 'Subject';
    case 'header':
      return 'X-Header'; // caller should supply value as "Header: value" but we normalise
    default:
      return field;
  }
}

// Build a single test string for one condition
function buildTest(cond: SieveCondition): string {
  const { field, operator, value } = cond;

  // Size tests are special
  if (field === 'size') {
    const comp = operator === 'greater-than' ? ':over' : ':under';
    return `size ${comp} ${parseInt(value, 10) || 0}`;
  }

  // Header/envelope tests
  const header = fieldToHeader(field);

  let matchType: string;
  let negate = false;

  switch (operator) {
    case 'is':
      matchType = ':is';
      break;
    case 'contains':
      matchType = ':contains';
      break;
    case 'not-contains':
      matchType = ':contains';
      negate = true;
      break;
    case 'matches':
      matchType = ':matches';
      break;
    // greater-than / less-than for non-size fields fall back to contains
    default:
      matchType = ':contains';
  }

  const escapedValue = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  const test = `header ${matchType} "${header}" "${escapedValue}"`;
  return negate ? `not ${test}` : test;
}

// Build the condition block (allOf / anyOf)
function buildConditionBlock(rule: SieveRule): string {
  const tests = rule.conditions.map(buildTest);

  if (tests.length === 0) return 'true';
  if (tests.length === 1) return tests[0];

  const op = rule.conditionOperator === 'allOf' ? 'allof' : 'anyof';
  const inner = tests.map(t => `    ${t}`).join(',\n');
  return `${op}(\n${inner}\n  )`;
}

// Build action lines for a rule
function buildActions(actions: SieveAction[]): string {
  if (actions.length === 0) return '    keep;';
  return actions
    .map(action => {
      switch (action.type) {
        case 'fileinto': {
          const folder = (action.value || 'INBOX').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
          return `    fileinto "${folder}";`;
        }
        case 'redirect': {
          const addr = (action.value || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
          return `    redirect "${addr}";`;
        }
        case 'discard':
          return '    discard;';
        case 'keep':
          return '    keep;';
        case 'flag':
          return '    addflag "\\\\Flagged";';
        case 'vacation': {
          const msg = (action.value || 'I am out of office.').replace(/\\/g, '\\\\').replace(/"/g, '\\"');
          return `    vacation "${msg}";`;
        }
        default:
          return '    keep;';
      }
    })
    .join('\n');
}

// --- public API --------------------------------------------------------

/**
 * Generate a complete Sieve script from a list of SieveRule objects.
 */
export function generateSieveScript(rules: SieveRule[]): string {
  const activeRules = rules.filter(r => r.enabled);
  const requires = collectRequires(activeRules);

  const lines: string[] = [];

  // Preamble
  lines.push('# Generated by Sagittarius');
  lines.push('# Do not edit manually unless you know Sieve syntax.');
  lines.push('');

  if (requires.length > 0) {
    const reqList = requires.map(r => `"${r}"`).join(', ');
    lines.push(`require [${reqList}];`);
    lines.push('');
  }

  for (const rule of activeRules) {
    lines.push(`# Rule: ${rule.name}`);

    if (rule.conditions.length === 0) {
      // Unconditional rule
      lines.push('{');
      lines.push(buildActions(rule.actions));
      lines.push('}');
    } else {
      const condBlock = buildConditionBlock(rule);
      lines.push(`if ${condBlock}`);
      lines.push('{');
      lines.push(buildActions(rule.actions));
      lines.push('}');
    }

    lines.push('');
  }

  return lines.join('\n');
}
